spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?serverTimezone=UTC
    username: root
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
