
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?serverTimezone=UTC
    username: root
    password: mysql2020


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8070
